#' Annotate text with sentiment scores
#'
#' @description
#' Annotates a character vector or a data frame of texts using
#' \code{\link[udpipe]{udpipe}} (providing
#' a model where necessary) and joins the results with a selected sentiment
#' lexicon.
#'
#'
#' @keywords functions
#' @param x A character vector, a data frame, or a list of texts.
#' @param model A UDpipe model used for annotation. The following options are
#'   supported:
#'   \itemize{
#'     \item{\code{NULL} (default): The function will automatically download and
#'       load the default Italian model (`italian-isdt`). Requires an internet
#'       connection on first use.}
#'     \item{\code{"local"}: Searches for a single `.udpipe` model file in the
#'       current working directory.}
#'     \item{A character string providing the full path to a `.udpipe` file
#'       ("path/to/model").}
#'     \item{A model object already loaded with
#'       \code{\link[udpipe]{udpipe_load_model}}. This is the most efficient
#'       option for repeated calls.}
#'   }
#' @param text_field A character string specifying the name of the column
#'   containing the text to be parsed.
#'   If `NULL` (the default), the function will try to detect column named
#'   "text".
#' @param docid_field A character string specifying the name of the column
#'   containing document identifiers. If `NULL` (the default), the function
#'   will try to detect a column named "doc_id"; if not found,
#'   IDs will be automatically generated.
#' @param dict The name of the lexicon to use. Can be one of the Sentix family
#'   (`"sentix"`, `"MAL"`) or ELIta family (`"elita_VAD"`,
#'   `"elita_basic"`). Defaults to `"sentix"`.
#' @param rescale Character string indicating the rescaling method for scores:
#'   `"default"` (for the lexicon), `"none"`, `"centered"`, `"normalized"`.
#'   Defaults to `"default"`.
#'   Passed to [get_elita()].
#' @param ... Additional arguments passed to
#'   the lexicon retrieval function (see [get_sentix()], [get_elita()]).
#'   OR to \code{\link[udpipe]{udpipe}} and subsequently to
#'   \code{\link[udpipe]{udpipe_annotate}}.
#'   Note: \code{tagger = "none"} is not supported (it will be ignored),
#'   as POS tagging is required for lemmatization and punctuation filtering.
#' @param simplify Logical. Defaults to `TRUE`. If `FALSE`, returns standard
#'   UDpipe columns (see Details).
#'
#' @details
#'
#' This function uses \code{\link[udpipe]{udpipe}} to process the
#' input texts, then joins the tokenized output with the specified lexicon, using
#' *dplyr* \code{\link[dplyr]{join}}. It performs two main steps:
#' \enumerate{
#'   \item \strong{Parsing:} Texts are tokenized, tagged, and lemmatized. For
#'     larger corpora, the function supports parallel processing by passing
#'     the argument \code{parallel.cores} to \code{\link[udpipe]{udpipe}}.
#'   \item \strong{Matching:} The parsed tokens are joined with the selected
#'     lexicon using \code{\link[dplyr]{left_join}}.
#' }
#'   All tokens are thus preserved in the output to maintain context, with
#'   \code{NA} assigned to tokens not found in the lexicon.
#' @return A `tibble` with one row per token, containing the following
#'   columns: `doc_id`, `sentence_id`, `token_id`, `token`, `lemma`, `upos`, one
#'   or more sentiment score columns, named after those of the selected lexicon.
#'
#'   When `simplify = FALSE` it will include standard UDpipe columns (see
#'   \code{\link[udpipe]{as.data.frame.udpipe_connlu}}), plus sentiment score
#'   columns.
#'
#' @export
#' @importFrom udpipe udpipe_annotate udpipe_download_model udpipe_load_model
#' @importFrom dplyr left_join
#'
#' @seealso [get_sentix()], [get_elita()], [sentix_summarize()]
#'
#' @examples
#' \dontrun{
#' # Auto-download model
#' ann_df <- sentix_annotate("Oggi è una bella giornata")
#'
#' # Use a local model file in the working directory (i.e. if already
#' # downloaded)
#' ann_df <- sentix_annotate("Uso un modello locale.", model = "local")
#'
#' # Use specific model path and lexicon
#' ann_df <- sentix_annotate("Oggi è una bella giornata",
#'     model = "path/to/model.udpipe",
#'     dict = "elita_VAD")
#'
#' # With a data frame, and a loaded model
#' data("recensioni_tv")
#' model <- udpipe::udpipe_load_model("italian-isdt-ud-2.5-191206.udpipe")
#' ann_df <- sentix_annotate(recensioni_tv, model = model)
#' )
#' }
sentix_annotate <- function(x,
                            model = NULL,
                            text_field = NULL,
                            docid_field = NULL,
                            dict = "sentix",
                            rescale = "default",
                            simplify = TRUE,
                            ...) {
  # --- Input Handling ---
  
  # if NULL, doc_id will be generated by Udpipe
  doc_id_vec <- NULL
  
  if (is.character(x)) {
    # a character vector
    text_vec <- x
    
    # NEW: Check if input vector already has names (doc_id)
    if (!is.null(names(x))) {
      doc_id_vec <- names(x)
    }
    
    # doc_id passed as argument overwrites names(x) if present
    if (!is.null(docid_field)) {
      # Controllo lunghezza
      if (length(docid_field) == length(text_vec)) {
        doc_id_vec <- docid_field
      } else {
        warning(
          sprintf(
            "Length of 'docid_field' (%d) does not match text length (%d). Generating default document identifiers.",
            length(docid_field),
            length(text_vec)
          )
        )
        # Reset doc_id_vec to NULL to let udpipe generate generic IDs
        doc_id_vec <- NULL
      }
    }
    
  } else if (is.data.frame(x)) {
    # a data frame
    cols <- names(x)
    
    # --- 1. Text Column ---
    if (is.null(text_field)) {
      text_col_idx <- grep("^text$", cols, ignore.case = TRUE)
      if (length(text_col_idx) == 0) {
        stop("Input is a data frame but no 'text' column found and argument 'text' is NULL.")
      }
      text_vec <- x[[cols[text_col_idx[1]]]]
    } else {
      if (!text_field %in% cols) {
        stop(
          sprintf(
            "Column '%s' specified in 'text_field' argument not found.",
            text_field
          )
        )
      }
      text_vec <- x[[text_field]]
    }
    
    # --- 2. doc_id column ---
    if (is.null(docid_field)) {
      doc_id_idx <- grep("^doc_id$", cols, ignore.case = TRUE)
      if (length(doc_id_idx) > 0) {
        doc_id_vec <- x[[cols[doc_id_idx[1]]]]
      }
    } else {
      if (docid_field %in% cols) {
        doc_id_vec <- x[[docid_field]]
      } else {
        warning(
          sprintf(
            "Column '%s' not found in data frame. The provided 'docid_field' argument is ignored.\nGenerating default document identifiers.",
            docid_field
          )
        )
      }
    }
  } else if (is.list(x)) {
    text_vec <- NULL
  } else {
    stop("Input 'x' must be a data frame, a character vector, or a list.")
  }
  
  # --- Get Lexicon ---
  
  sentix_family <- c("sentix", "MAL")
  elita_family <- c("elita_VAD", "elita_basic")
  supported_lex <- c("sentix", "MAL", "elita_VAD", "elita_basic")
  
  # separate arguments inherited from get_ functions and from udpipe.
  args <- list(...)
  
  # force tagging
  if ("tagger" %in% names(args)) {
    if (args$tagger == "none") {
      warning("Argument 'tagger = \"none\"'. POS tagging and is required.")
      args$tagger <- NULL
    }
  }
  
  if (dict %in% sentix_family) {
    include_poly <- if ("polypathy" %in% names(args)) {
      args$polypathy
    } else {
      FALSE
    }
    lex_data <- get_sentix(dict = dict,
                           polypathy = include_poly)
  } else if (dict %in% elita_family) {
    lex_data <- get_elita(dict = dict, rescale = rescale)
  } else {
    stop(paste(
      "Unknown lexicon. Choose from:",
      paste(supported_lex, collapse = ", ")
    ))
  }
  
  # --- Model Handling ---
  if (is.null(model)) {
    # model = NULL
    message("No model provided. Downloading default Italian model...")
    tryCatch({
      dl <- udpipe::udpipe_download_model(language = "italian")
      model <- udpipe::udpipe_load_model(dl$file_model)
    }, error = function(e) {
      stop(
        "Failed to download/load default Italian model. Please provide a 'model' argument manually.\nError: ",
        e$message
      )
    })
    # model = "local"
  } else if (is.character(model) && model == "local") {
    message("Searching for a local .udpipe model in the working directory...")
    local_models <- list.files(path = ".", pattern = "\\.udpipe$")
    
    if (length(local_models) == 0) {
      stop("Model = 'local' was specified, but no .udpipe file was found.")
    } else if (length(local_models) > 1) {
      stop(
        "Found multiple .udpipe files.\n",
        "Please specify the exact filename. Found: ",
        paste(local_models, collapse = ", ")
      )
    } else {
      message("Found model: ", local_models[1])
      model <- udpipe::udpipe_load_model(local_models[1])
    }
  } else if (is.character(model)) {
    # model = "path/to/model"
    if (file.exists(model)) {
      model <- udpipe::udpipe_load_model(model)
    } else {
      stop("Model file not found: ", model)
    }
  }
  
  # --- Tokenize ---
  
  # arguments for udpipe
  udpipe_args <- args
  
  # cleanup arguments meant for other functions/internal logic
  udpipe_args$polypathy <- NULL
  udpipe_args$object <- model
  
  
  if (is.data.frame(x)) {
    if (!is.null(doc_id_vec)) {
      udpipe_args$x <- data.frame(doc_id = doc_id_vec,
                                  text = text_vec,
                                  stringsAsFactors = FALSE)
    } else {
      udpipe_args$x <- data.frame(text = text_vec, stringsAsFactors = FALSE)
    }
  } else if (is.list(x)) {
    udpipe_args$x <- x
    
    if (!is.null(docid_field)) {
      if (length(docid_field) == length(x)) {
        names(udpipe_args$x) <- docid_field
      } else {
        warning(
          sprintf(
            "sentix: Length of 'docid_field' (%d) does not match list length (%d). ID ignored.",
            length(docid_field),
            length(x)
          )
        )
      }
    }
  } else {
    # if character vector
    udpipe_args$x <- text_vec
    if (!is.null(doc_id_vec)) {
      names(udpipe_args$x) <- doc_id_vec
    }
  }
  
  # cautelly remove doc_id from args to avoid conflicts
  udpipe_args$doc_id <- NULL
  
  ud_out <- as.data.frame(do.call(udpipe::udpipe, udpipe_args))
  
  # --- Join ---
  
  lex_cols <- names(lex_data)
  
  # lemma or word -> token
  if ("lemma" %in% lex_cols) {
    by_args <- c("lemma" = "lemma")
  } else {
    # word -> temp lowercase column of the token for matching
    ud_out$token_lower <- tolower(ud_out$token)
    by_args <- c("token_lower" = "word")
  }
  
  annotated <- dplyr::left_join(ud_out, lex_data, by = by_args)
  
  # remove temp lowercase column
  if ("token_lower" %in% names(annotated)) {
    annotated$token_lower <- NULL
  }
  
  # --- Simplify ---
  if (simplify) {
    cols_to_keep <- c("doc_id",
                      "sentence_id",
                      "token_id",
                      "token",
                      "lemma",
                      "upos",
                      names(lex_data)[!names(lex_data) %in% c("lemma", "word")])
    
    # check existing columns
    cols_to_keep <- intersect(cols_to_keep, names(annotated))
    
    annotated <- annotated |>
      dplyr::select(dplyr::all_of(cols_to_keep))
  }
  
  return(annotated)
}
